theme: jekyll-theme-cayman
title: "Ramses Alexander Coraspe Valdez </br> Computer Vision algorithms and Deep Learning"
description: "The repository contains basic experiments using machine learning algorithms with python"
