theme: jekyll-theme-cayman
title: "Ramses Alexander Coraspe Valdez </br> Computer Vision algorithms and Deep Learning with Python"
description: "This repository contains information on the basic techniques and algorithms used in computer image processing, in addition to some projects related to pattern recognition using deep learning with Python"
